name: "Manual Release - Main"

on:
  workflow_dispatch:
    inputs:
      workflowPreset: # Customize the CMake workflow type here (Release, RelWithDebInfo, MinSizeRel, Debug)
        description: 'Configure/Build/Test/Package configuration'
        required: false
        default: 'Release' 
        type: choice
        options:
        - 'Release'
        - 'RelWithDebInfo'
        - 'MinSizeRel'
        - 'Debug'

jobs:
  build:
    runs-on: windows-latest

    # defaults:
    #   run:
    #     shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake

    - uses: actions/checkout@v4

    - name: Set PATH to include MinGW-W64 from MSYS2
      run: |
        $path1 = "C:/msys64/mingw64/bin"
        $path2 = "C:/msys64/usr/bin"
        echo "$path1`n$path2`n$(Get-Content $env:GITHUB_PATH)" | Set-Content $env:GITHUB_PATH

    - name: Debug List Files 1
      run: Get-ChildItem C:/msys64/mingw64/bin/*cmake*.exe

    - name: Debug List Files 2
      run: Get-ChildItem C:/msys64/mingw64/bin/*gcc*.exe

    - name: Debug List Files 3
      run: Get-ChildItem C:/msys64/mingw64/bin/*

    - name: Debug List Files 4
      run: Get-ChildItem C:/msys64/usr/bin/*

    - name: Check PATH
      run: |
        echo $env:PATH
        which cmake
        which gcc

    - name: Run CMake
      run: cmake --workflow --preset ${{inputs.workflowPreset}} --fresh

    # Zip the publish artifacts
    - name: Zip the publish artifacts
      working-directory: ${{github.workspace}}
      shell: pwsh
      run: |
        Add-Type -assembly 'System.IO.Compression'
        Add-Type -assembly 'System.IO.Compression.FileSystem'
        [System.IO.Compression.ZipArchive]$zipFile = [System.IO.Compression.ZipFile]::Open('Release.zip', ([System.IO.Compression.ZipArchiveMode]::Create))
        $filesToZip = (Get-ChildItem -Path build/* -Include "RE2RRandomizer.exe", "libRE2RRandomizerHook.dll").fullname
        foreach ($fileToZip in $filesToZip) {
            [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zipFile, $fileToZip, (Split-Path $fileToZip -Leaf))
        }
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zipFile, 'LICENSE', 'LICENSE')
        $zipFile.Dispose()

    # Pushes the release
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{inputs.workflowPreset}}-build"
        prerelease: true
        title: 'Manual Build [main] - v1.0.0 Release'
        files: |
          RE2RRandomizer-v1.0.0-1234-${{inputs.workflowPreset}}.zip
        # Name-Version String-Build Number-Build Type.zip
